info:
  name: Create Custom Configuration
  type: http
  seq: 1

http:
  method: POST
  url: "{{base_url}}/api/v1/custom-configurations"
  body:
    type: json
    data: "{\r

      \    \"name\": \"currency_rates\",\r

      \    \"description\": \"Configuration for tender comittee limit\",\r

      \    \"detail\": [\r

      \        {\r

      \            \"key\": \"usd_to_idr\",\r

      \            \"value\": 15000,\r

      \            \"note\": \"Valid value is integer\"\r

      \        },\r

      \        {\r

      \            \"key\": \"idr_to_usd\",\r

      \            \"value\": 0,\r

      \            \"note\": \"Valid value is integer\"\r

      \        }\r

      \    ]\r

      }"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: success
    request:
      url: "{{base_url}}/api/v1/custom-configurations"
      method: POST
      body:
        type: json
        data: "{\r

          \    \"name\": \"usd_rate\",\r

          \    \"description\": \"Configuration for USD rate to Rupiah\",\r

          \    \"detail\": [\r

          \        {\r

          \            \"key\": \"rate\",\r

          \            \"value\": 15000,\r

          \            \"note\": \"Valid value is integer\"\r

          \        }\r

          \    ]\r

          }"
    response:
      statusText: "201"
      headers:
        - name: Content-Type
          value: application/json; charset=UTF-8
        - name: Vary
          value: Origin
        - name: Date
          value: Sun, 12 Nov 2023 10:15:26 GMT
        - name: Content-Length
          value: "102"
      body:
        type: json
        data: |-
          {
              "process_time": "269ms",
              "status": "success",
              "code": "",
              "message": "Create custom configuration succeed"
          }
  - name: failed request validation
    request:
      url: "{{base_url}}/api/v1/custom-configurations"
      method: POST
      body:
        type: json
        data: "{\r

          \    \"name\": \"usd_rate\",\r

          \    \"detail\": [\r

          \        {\r

          \            \"key\": \"rate\",\r

          \            \"value\": 15000,\r

          \            \"note\": \"Valid value is integer\"\r

          \        }\r

          \    ]\r

          }"
    response:
      statusText: "400"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: "{\r

          \    \"process_time\": \"0ms\",\r

          \    \"status\": \"failed\",\r

          \    \"code\": \"17\",\r

          \    \"message\": \"Description: cannot be blank.\",\r

          \    \"error_data\": {\r

          \        \"title\": \"Failed\",\r

          \        \"description\": \"Description: cannot be blank.\",\r

          \        \"icon\": \"https://storage.googleapis.com/phi-dev-bucket/assets/failed-icon.png\",\r

          \        \"primary_text\": \"OK\",\r

          \        \"secondary_text\": \"\",\r

          \        \"primary_link\": \"\",\r

          \        \"secondary_link\": \"\",\r

          \        \"dismissed_link\": \"\"\r

          \    }\r

          }"
