info:
  name: Delete custom configuration
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc42"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: success
    request:
      url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc42"
      method: DELETE
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json; charset=UTF-8
        - name: Vary
          value: Origin
        - name: Date
          value: Wed, 22 Nov 2023 02:44:40 GMT
        - name: Content-Length
          value: "101"
      body:
        type: json
        data: |-
          {
              "process_time": "93ms",
              "status": "success",
              "code": "",
              "message": "Delete custom configuration succeed"
          }
  - name: failed data not found
    request:
      url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc41"
      method: DELETE
    response:
      statusText: "404"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: "{\r

          \    \"process_time\": \"4ms\",\r

          \    \"status\": \"failed\",\r

          \    \"code\": \"05\",\r

          \    \"message\": \"Data not found\",\r

          \    \"error_data\": {\r

          \        \"title\": \"Failed\",\r

          \        \"description\": \"Data not found\",\r

          \        \"icon\": \"https://storage.googleapis.com/phi-dev-bucket/assets/failed-icon.png\",\r

          \        \"primary_text\": \"OK\",\r

          \        \"secondary_text\": \"\",\r

          \        \"primary_link\": \"\",\r

          \        \"secondary_link\": \"\",\r

          \        \"dismissed_link\": \"\"\r

          \    }\r

          }"
