info:
  name: Get custom configuration by ID
  type: http
  seq: 3

http:
  method: GET
  url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc42"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: success
    request:
      url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc42"
      method: GET
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json; charset=UTF-8
        - name: Vary
          value: Origin
        - name: Date
          value: Wed, 22 Nov 2023 02:38:30 GMT
        - name: Content-Length
          value: "450"
      body:
        type: json
        data: |-
          {
              "process_time": "27ms",
              "status": "success",
              "code": "",
              "message": "Get custom configuration succeed",
              "data": {
                  "id": "e1efb8b1-42c1-412e-92d7-6af3e58cbc42",
                  "name": "usd_rate",
                  "description": "Configuration for USD rate to Rupiah",
                  "detail": [
                      {
                          "key": "rate",
                          "value": 15000,
                          "note": "Valid value is integer"
                      }
                  ],
                  "created_at": "12-11-2023 17:32:33",
                  "created_by": "Super Admin",
                  "updated_at": "12-11-2023 17:32:33",
                  "updated_by": "Super Admin",
                  "deleted_at": "",
                  "deleted_by": ""
              }
          }
  - name: failed data not found
    request:
      url: "{{base_url}}/api/v1/custom-configurations/e1efb8b1-42c1-412e-92d7-6af3e58cbc41"
      method: GET
    response:
      statusText: "404"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: "{\r

          \    \"process_time\": \"5ms\",\r

          \    \"status\": \"failed\",\r

          \    \"code\": \"05\",\r

          \    \"message\": \"Data not found\",\r

          \    \"error_data\": {\r

          \        \"title\": \"Failed\",\r

          \        \"description\": \"Data not found\",\r

          \        \"icon\": \"https://storage.googleapis.com/phi-dev-bucket/assets/failed-icon.png\",\r

          \        \"primary_text\": \"OK\",\r

          \        \"secondary_text\": \"\",\r

          \        \"primary_link\": \"\",\r

          \        \"secondary_link\": \"\",\r

          \        \"dismissed_link\": \"\"\r

          \    }\r

          }"
