info:
  name: Get Notification Configuration
  type: http
  seq: 2

http:
  method: GET
  url: "{{base_url}}/api/v1/projects/tasks/notifications"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: success
    request:
      url: "{{base_url}}/api/v1/projects/tasks/notifications"
      method: GET
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
              "process_time": "27ms",
              "status": "success",
              "code": "",
              "message": "Get project task notification succeed",
              "data": {
                  "id": "4b582f02-db06-42f3-ae47-9c4aaad38eee",
                  "frequency": "weekly",
                  "recipients": [
                      {
                          "id": "e8e968e7-77ce-4668-b8d6-fc80e083af67",
                          "full_name": "Super Admin",
                          "status": "active",
                          "email": "super_admin@gmail.com"
                      }
                  ]
              }
          }
